services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform-portfolio-infra
    working_dir: /infra/terraform
    volumes:
      - .:/infra
    env_file:
      - tf-ansible.env
    entrypoint: tail -f /dev/null
    stdin_open: true
    tty: true

  ansible:
    image: cytopia/ansible:latest
    container_name: ansible-portfolio-infra
    working_dir: /infra/ansible
    volumes:
        - .:/infra
        - ./.ssh/id_ed25519_hetzner:/root/.ssh/id_ed25519_hetzner:ro
        - ./.ssh/id_ed25519_hetzner.pub:/root/.ssh/id_ed25519_hetzner.pub:ro
    env_file:
      - tf-ansible.env
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    stdin_open: true
    tty: true