services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform-portfolio-infra
    working_dir: /infra/terraform
    volumes:
      - :/infra
      - ~/.ssh:/root/.ssh:ro
    env_file:
      - tf-ansible.env
    stdin_open: true
    tty: true

  ansible:
    image: cytopia/ansible:latest
    container_name: ansible-portfolio-infra
    working_dir: /infra/ansible
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh:ro
    env_file:
      - tf-ansible.env
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    stdin_open: true
    tty: true